services:
  db:
    image: postgres:16
    container_name: typinng-game-db
    environment:
      POSTGRES_DB: typing_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: to
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: