spring.application.name=backend

spring.datasource.url = jdbc:postgresql://localhost:5432/typing_game
spring.datasource.username = postgres
spring.datasource.password=to

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true